* lisp

This contains: ~parser~ and ~tokenizer~.

This project isn't a library. You are supposed to clone this repository and modify it to your needs.

Quick example: ~odin run .~

#+BEGIN_SRC odin :tangle example.odin
package example

import "core:log"
import "core:os"
import "parser"

main :: proc() {
	log.Level_Headers = {
		0 ..< 10 = "debug: ",
		10 ..< 20 = "info: ",
		20 ..< 30 = "warn: ",
		30 ..< 40 = "error: ",
		40 ..< 50 = "fatal: ",
	}

	log_opt := log.Options{.Level}
	if os.is_tty(os.stdin) do log_opt += {.Terminal_Color}

	context.logger = log.create_console_logger(opt = log_opt)
	defer log.destroy_console_logger(context.logger)

	contents, err := os.read_entire_file_from_path("example.lisp", context.temp_allocator)
	if err != nil do return

	elements := parser.parse(string(contents[:]), "example.lisp") // err := default_error_handler

	for e in elements {
		parser.print(e)
	}
}
#+END_SRC

** Motivation

I find lisp to have the easiest syntax, both to read and to parse. This has the main goal of simplifying writing anything that relates to lisp. Few assumptions are made on purpose, so the user can hack this very easily and expand this to a custom DSL, lisp interpreter or a transpiler.

** Notes

This project isn't AI assisted, and I'm not very familiar with Lisp syntax. Expect it to don't follow the same style from other Lisp interpreters like Common Lisp, Clojure, Emacs Lisp or Racket, but many ideas are borrowed.

Some notable tokenizing differences:

| Syntax    | This lisp   | Common Lisp |
|-----------+-------------+-------------|
| Character | 'r'         | #\r         |
| Boolean   | true, false | t, nil      |

** License

zlib license.
